# Character-Level LSTM in PyTorch

In this notebook, represent LSTM with PyTorch. The network will train character by character on some text, then generate new text character by character. As an example, It will be trained on Anna Karenina. **This model will be able to generate new text based on the text from the book!**

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn).

In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

## Load in Data

In [2]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

### Tokenization

In the cells, below, I'm creating a couple **dictionaries** to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [4]:
# encode the text and map each character to an integer and vice versa

# 1. int2char, maps integers to characters
# 2. char2int, maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}
print(int2char.items())

# encode the text
encoded = np.array([char2int[ch] for ch in text])

dict_items([(0, 'C'), (1, '4'), (2, 'Q'), (3, 't'), (4, '2'), (5, 'X'), (6, 'R'), (7, 'l'), (8, '*'), (9, '0'), (10, 'x'), (11, '('), (12, 'v'), (13, 'h'), (14, '-'), (15, 'I'), (16, 'U'), (17, '_'), (18, 'J'), (19, '@'), (20, '$'), (21, '\n'), (22, '5'), (23, 'g'), (24, ')'), (25, 'c'), (26, 'f'), (27, 'a'), (28, 's'), (29, '.'), (30, 'Y'), (31, '?'), (32, '3'), (33, '/'), (34, 'w'), (35, 'A'), (36, 'D'), (37, 'H'), (38, 'F'), (39, 'o'), (40, '8'), (41, '7'), (42, '`'), (43, 'G'), (44, '!'), (45, '1'), (46, ','), (47, 'W'), (48, 'n'), (49, 'E'), (50, '&'), (51, "'"), (52, 'Z'), (53, ';'), (54, 'k'), (55, 'q'), (56, 'u'), (57, '"'), (58, 'L'), (59, '9'), (60, 'd'), (61, ' '), (62, '6'), (63, 'i'), (64, 'y'), (65, 'j'), (66, ':'), (67, 'r'), (68, 'B'), (69, 'S'), (70, 'N'), (71, 'p'), (72, 'e'), (73, 'z'), (74, 'V'), (75, 'P'), (76, 'M'), (77, 'T'), (78, 'K'), (79, 'b'), (80, '%'), (81, 'O'), (82, 'm')])


## Encoded text

In [5]:
encoded[:100]

array([ 0, 13, 27, 71,  3, 72, 67, 61, 45, 21, 21, 21, 37, 27, 71, 71, 64,
       61, 26, 27, 82, 63,  7, 63, 72, 28, 61, 27, 67, 72, 61, 27,  7,  7,
       61, 27,  7, 63, 54, 72, 53, 61, 72, 12, 72, 67, 64, 61, 56, 48, 13,
       27, 71, 71, 64, 61, 26, 27, 82, 63,  7, 64, 61, 63, 28, 61, 56, 48,
       13, 27, 71, 71, 64, 61, 63, 48, 61, 63,  3, 28, 61, 39, 34, 48, 21,
       34, 27, 64, 29, 21, 21, 49, 12, 72, 67, 64,  3, 13, 63, 48])

## Pre-processing the data
Network exepts **one-hot encoded characters**

In [6]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((np.multiply(*arr.shape), n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [7]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


## Making training mini-batches

Before training data will be divided into mini-batches.
<br>

In [8]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    batch_size_total = batch_size * seq_length
    # total number of batches that can be made
    n_batches = len(arr)//batch_size_total
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size_total]
    # Reshape into batch_size rows
    arr = arr.reshape((batch_size, -1))
    
    # iterate through the array, one sequence at a time
    for n in range(0, arr.shape[1], seq_length):
        # The features
        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

### Test Implementation

Now I'll make some data sets to check out what's going on with batch data. Here, as an example, with batch size of 8 and 50 sequence steps.

In [9]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)

In [10]:
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])

# data should be shifted over one step for y
print('\ny\n', y[:10, :10])

x
 [[ 0 13 27 71  3 72 67 61 45 21]
 [28 39 48 61  3 13 27  3 61 27]
 [72 48 60 61 39 67 61 27 61 26]
 [28 61  3 13 72 61 25 13 63 72]
 [61 28 27 34 61 13 72 67 61  3]
 [25 56 28 28 63 39 48 61 27 48]
 [61 35 48 48 27 61 13 27 60 61]
 [81 79  7 39 48 28 54 64 29 61]]

y
 [[13 27 71  3 72 67 61 45 21 21]
 [39 48 61  3 13 27  3 61 27  3]
 [48 60 61 39 67 61 27 61 26 39]
 [61  3 13 72 61 25 13 63 72 26]
 [28 27 34 61 13 72 67 61  3 72]
 [56 28 28 63 39 48 61 27 48 60]
 [35 48 48 27 61 13 27 60 61 28]
 [79  7 39 48 28 54 64 29 61 57]]


---
## Defining the network with PyTorch

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```                           
`input_size` is the number of characters this cell expects to see as sequential input
`n_hidden` is the number of units in the hidden layers in the cell    
`n_layers` is the number of layers    
`dropout_prob` is the dropout probability

In [11]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

Training on GPU!


In [12]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## define the LSTM
        self.lstm = nn.LSTM(len(self.chars), n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        ## define a dropout layer
        self.dropout = nn.Dropout(drop_prob)
        
        ## define the final, fully-connected output layer
        self.fc = nn.Linear(n_hidden, len(self.chars))
      
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ##  Get the outputs and the new hidden state from the lstm
        r_output, hidden = self.lstm(x, hidden)
        
        ##  pass through a dropout layer
        out = self.dropout(r_output)
        
        # Stack up LSTM outputs using view
        out = out.contiguous().view(-1, self.n_hidden)
        
        ## put x through the fully-connected layer
        out = self.fc(out)
        
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                      weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden
        

## Training

In [13]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.view(batch_size*seq_length))
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.view(batch_size*seq_length))
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

## Instantiating the model

In [14]:
# define and print the net
n_hidden=512
n_layers=2

net = CharRNN(chars, n_hidden, n_layers)
print(net)

CharRNN(
  (lstm): LSTM(83, 512, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5)
  (fc): Linear(in_features=512, out_features=83, bias=True)
)


In [15]:
batch_size = 128
seq_length = 10
n_epochs = 27 # start smaller just to testing initial behavior

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)

Epoch: 1/27... Step: 10... Loss: 3.2473... Val Loss: 3.2347
Epoch: 1/27... Step: 20... Loss: 3.1577... Val Loss: 3.1467
Epoch: 1/27... Step: 30... Loss: 3.1138... Val Loss: 3.1346
Epoch: 1/27... Step: 40... Loss: 3.1067... Val Loss: 3.1283
Epoch: 1/27... Step: 50... Loss: 3.1263... Val Loss: 3.1276
Epoch: 1/27... Step: 60... Loss: 3.1081... Val Loss: 3.1238
Epoch: 1/27... Step: 70... Loss: 3.0536... Val Loss: 3.1232
Epoch: 1/27... Step: 80... Loss: 3.1011... Val Loss: 3.1213
Epoch: 1/27... Step: 90... Loss: 3.0660... Val Loss: 3.1112
Epoch: 1/27... Step: 100... Loss: 3.0696... Val Loss: 3.0904
Epoch: 1/27... Step: 110... Loss: 2.9959... Val Loss: 3.0407
Epoch: 1/27... Step: 120... Loss: 2.9881... Val Loss: 2.9539
Epoch: 1/27... Step: 130... Loss: 2.9240... Val Loss: 2.9243
Epoch: 1/27... Step: 140... Loss: 2.7555... Val Loss: 2.8232
Epoch: 1/27... Step: 150... Loss: 2.6804... Val Loss: 2.7172
Epoch: 1/27... Step: 160... Loss: 2.6114... Val Loss: 2.6272
Epoch: 1/27... Step: 170... Loss:

Epoch: 1/27... Step: 1350... Loss: 1.6281... Val Loss: 1.6388
Epoch: 1/27... Step: 1360... Loss: 1.5561... Val Loss: 1.6339
Epoch: 1/27... Step: 1370... Loss: 1.5816... Val Loss: 1.6347
Epoch: 1/27... Step: 1380... Loss: 1.7323... Val Loss: 1.6306
Epoch: 1/27... Step: 1390... Loss: 1.6063... Val Loss: 1.6256
Epoch: 2/27... Step: 1400... Loss: 1.6051... Val Loss: 1.6303
Epoch: 2/27... Step: 1410... Loss: 1.5341... Val Loss: 1.6229
Epoch: 2/27... Step: 1420... Loss: 1.6312... Val Loss: 1.6279
Epoch: 2/27... Step: 1430... Loss: 1.5922... Val Loss: 1.6187
Epoch: 2/27... Step: 1440... Loss: 1.5881... Val Loss: 1.6225
Epoch: 2/27... Step: 1450... Loss: 1.6041... Val Loss: 1.6116
Epoch: 2/27... Step: 1460... Loss: 1.5796... Val Loss: 1.6134
Epoch: 2/27... Step: 1470... Loss: 1.5394... Val Loss: 1.6151
Epoch: 2/27... Step: 1480... Loss: 1.6056... Val Loss: 1.6099
Epoch: 2/27... Step: 1490... Loss: 1.6614... Val Loss: 1.6075
Epoch: 2/27... Step: 1500... Loss: 1.5308... Val Loss: 1.6076
Epoch: 2

Epoch: 2/27... Step: 2680... Loss: 1.3975... Val Loss: 1.4717
Epoch: 2/27... Step: 2690... Loss: 1.3562... Val Loss: 1.4736
Epoch: 2/27... Step: 2700... Loss: 1.4403... Val Loss: 1.4745
Epoch: 2/27... Step: 2710... Loss: 1.4769... Val Loss: 1.4704
Epoch: 2/27... Step: 2720... Loss: 1.2886... Val Loss: 1.4718
Epoch: 2/27... Step: 2730... Loss: 1.5179... Val Loss: 1.4657
Epoch: 2/27... Step: 2740... Loss: 1.4060... Val Loss: 1.4675
Epoch: 2/27... Step: 2750... Loss: 1.3578... Val Loss: 1.4811
Epoch: 2/27... Step: 2760... Loss: 1.3188... Val Loss: 1.4699
Epoch: 2/27... Step: 2770... Loss: 1.3725... Val Loss: 1.4720
Epoch: 2/27... Step: 2780... Loss: 1.3863... Val Loss: 1.4708
Epoch: 2/27... Step: 2790... Loss: 1.9398... Val Loss: 1.4647
Epoch: 3/27... Step: 2800... Loss: 1.4492... Val Loss: 1.4854
Epoch: 3/27... Step: 2810... Loss: 1.4151... Val Loss: 1.4635
Epoch: 3/27... Step: 2820... Loss: 1.4288... Val Loss: 1.4685
Epoch: 3/27... Step: 2830... Loss: 1.3938... Val Loss: 1.4616
Epoch: 3

Epoch: 3/27... Step: 4010... Loss: 1.3342... Val Loss: 1.4110
Epoch: 3/27... Step: 4020... Loss: 1.3569... Val Loss: 1.4151
Epoch: 3/27... Step: 4030... Loss: 1.3089... Val Loss: 1.4111
Epoch: 3/27... Step: 4040... Loss: 1.2851... Val Loss: 1.4156
Epoch: 3/27... Step: 4050... Loss: 1.3324... Val Loss: 1.4093
Epoch: 3/27... Step: 4060... Loss: 1.3426... Val Loss: 1.4071
Epoch: 3/27... Step: 4070... Loss: 1.3001... Val Loss: 1.4112
Epoch: 3/27... Step: 4080... Loss: 1.3848... Val Loss: 1.4072
Epoch: 3/27... Step: 4090... Loss: 1.3807... Val Loss: 1.4072
Epoch: 3/27... Step: 4100... Loss: 1.4162... Val Loss: 1.4146
Epoch: 3/27... Step: 4110... Loss: 1.3378... Val Loss: 1.4039
Epoch: 3/27... Step: 4120... Loss: 1.3104... Val Loss: 1.4179
Epoch: 3/27... Step: 4130... Loss: 1.3966... Val Loss: 1.4212
Epoch: 3/27... Step: 4140... Loss: 1.3502... Val Loss: 1.4040
Epoch: 3/27... Step: 4150... Loss: 1.2844... Val Loss: 1.4090
Epoch: 3/27... Step: 4160... Loss: 1.3388... Val Loss: 1.4236
Epoch: 3

Epoch: 4/27... Step: 5340... Loss: 1.2837... Val Loss: 1.3774
Epoch: 4/27... Step: 5350... Loss: 1.2760... Val Loss: 1.3812
Epoch: 4/27... Step: 5360... Loss: 1.2719... Val Loss: 1.3790
Epoch: 4/27... Step: 5370... Loss: 1.2939... Val Loss: 1.3851
Epoch: 4/27... Step: 5380... Loss: 1.2993... Val Loss: 1.3768
Epoch: 4/27... Step: 5390... Loss: 1.2159... Val Loss: 1.3775
Epoch: 4/27... Step: 5400... Loss: 1.2190... Val Loss: 1.3813
Epoch: 4/27... Step: 5410... Loss: 1.3668... Val Loss: 1.3774
Epoch: 4/27... Step: 5420... Loss: 1.3092... Val Loss: 1.3792
Epoch: 4/27... Step: 5430... Loss: 1.3086... Val Loss: 1.3792
Epoch: 4/27... Step: 5440... Loss: 1.3275... Val Loss: 1.3774
Epoch: 4/27... Step: 5450... Loss: 1.2832... Val Loss: 1.3731
Epoch: 4/27... Step: 5460... Loss: 1.3485... Val Loss: 1.3823
Epoch: 4/27... Step: 5470... Loss: 1.2736... Val Loss: 1.3728
Epoch: 4/27... Step: 5480... Loss: 1.2391... Val Loss: 1.3720
Epoch: 4/27... Step: 5490... Loss: 1.2979... Val Loss: 1.3784
Epoch: 4

Epoch: 5/27... Step: 6670... Loss: 1.1656... Val Loss: 1.3561
Epoch: 5/27... Step: 6680... Loss: 1.2976... Val Loss: 1.3617
Epoch: 5/27... Step: 6690... Loss: 1.2696... Val Loss: 1.3549
Epoch: 5/27... Step: 6700... Loss: 1.2609... Val Loss: 1.3581
Epoch: 5/27... Step: 6710... Loss: 1.1956... Val Loss: 1.3548
Epoch: 5/27... Step: 6720... Loss: 1.1773... Val Loss: 1.3550
Epoch: 5/27... Step: 6730... Loss: 1.2680... Val Loss: 1.3532
Epoch: 5/27... Step: 6740... Loss: 1.2540... Val Loss: 1.3557
Epoch: 5/27... Step: 6750... Loss: 1.3057... Val Loss: 1.3525
Epoch: 5/27... Step: 6760... Loss: 1.3061... Val Loss: 1.3524
Epoch: 5/27... Step: 6770... Loss: 1.2346... Val Loss: 1.3539
Epoch: 5/27... Step: 6780... Loss: 1.2777... Val Loss: 1.3518
Epoch: 5/27... Step: 6790... Loss: 1.1873... Val Loss: 1.3523
Epoch: 5/27... Step: 6800... Loss: 1.2666... Val Loss: 1.3589
Epoch: 5/27... Step: 6810... Loss: 1.2705... Val Loss: 1.3541
Epoch: 5/27... Step: 6820... Loss: 1.2446... Val Loss: 1.3559
Epoch: 5

Epoch: 6/27... Step: 8000... Loss: 1.2494... Val Loss: 1.3429
Epoch: 6/27... Step: 8010... Loss: 1.2932... Val Loss: 1.3460
Epoch: 6/27... Step: 8020... Loss: 1.2616... Val Loss: 1.3444
Epoch: 6/27... Step: 8030... Loss: 1.2567... Val Loss: 1.3423
Epoch: 6/27... Step: 8040... Loss: 1.2767... Val Loss: 1.3462
Epoch: 6/27... Step: 8050... Loss: 1.2271... Val Loss: 1.3444
Epoch: 6/27... Step: 8060... Loss: 1.2574... Val Loss: 1.3458
Epoch: 6/27... Step: 8070... Loss: 1.2043... Val Loss: 1.3492
Epoch: 6/27... Step: 8080... Loss: 1.1493... Val Loss: 1.3438
Epoch: 6/27... Step: 8090... Loss: 1.2609... Val Loss: 1.3454
Epoch: 6/27... Step: 8100... Loss: 1.2148... Val Loss: 1.3431
Epoch: 6/27... Step: 8110... Loss: 1.2189... Val Loss: 1.3430
Epoch: 6/27... Step: 8120... Loss: 1.2013... Val Loss: 1.3457
Epoch: 6/27... Step: 8130... Loss: 1.2370... Val Loss: 1.3415
Epoch: 6/27... Step: 8140... Loss: 1.2137... Val Loss: 1.3447
Epoch: 6/27... Step: 8150... Loss: 1.1970... Val Loss: 1.3452
Epoch: 6

Epoch: 7/27... Step: 9330... Loss: 1.2877... Val Loss: 1.3329
Epoch: 7/27... Step: 9340... Loss: 1.1471... Val Loss: 1.3305
Epoch: 7/27... Step: 9350... Loss: 1.2130... Val Loss: 1.3346
Epoch: 7/27... Step: 9360... Loss: 1.2493... Val Loss: 1.3374
Epoch: 7/27... Step: 9370... Loss: 1.2219... Val Loss: 1.3391
Epoch: 7/27... Step: 9380... Loss: 1.2327... Val Loss: 1.3345
Epoch: 7/27... Step: 9390... Loss: 1.2497... Val Loss: 1.3347
Epoch: 7/27... Step: 9400... Loss: 1.2269... Val Loss: 1.3326
Epoch: 7/27... Step: 9410... Loss: 1.1733... Val Loss: 1.3347
Epoch: 7/27... Step: 9420... Loss: 1.1815... Val Loss: 1.3299
Epoch: 7/27... Step: 9430... Loss: 1.2313... Val Loss: 1.3339
Epoch: 7/27... Step: 9440... Loss: 1.2682... Val Loss: 1.3353
Epoch: 7/27... Step: 9450... Loss: 1.2238... Val Loss: 1.3324
Epoch: 7/27... Step: 9460... Loss: 1.1280... Val Loss: 1.3379
Epoch: 7/27... Step: 9470... Loss: 1.2304... Val Loss: 1.3396
Epoch: 7/27... Step: 9480... Loss: 1.2446... Val Loss: 1.3360
Epoch: 7

Epoch: 8/27... Step: 10650... Loss: 1.2568... Val Loss: 1.3248
Epoch: 8/27... Step: 10660... Loss: 1.1866... Val Loss: 1.3271
Epoch: 8/27... Step: 10670... Loss: 1.2164... Val Loss: 1.3274
Epoch: 8/27... Step: 10680... Loss: 1.1772... Val Loss: 1.3251
Epoch: 8/27... Step: 10690... Loss: 1.2122... Val Loss: 1.3238
Epoch: 8/27... Step: 10700... Loss: 1.2152... Val Loss: 1.3255
Epoch: 8/27... Step: 10710... Loss: 1.2832... Val Loss: 1.3228
Epoch: 8/27... Step: 10720... Loss: 1.1985... Val Loss: 1.3227
Epoch: 8/27... Step: 10730... Loss: 1.2293... Val Loss: 1.3238
Epoch: 8/27... Step: 10740... Loss: 1.2527... Val Loss: 1.3252
Epoch: 8/27... Step: 10750... Loss: 1.2395... Val Loss: 1.3298
Epoch: 8/27... Step: 10760... Loss: 1.2069... Val Loss: 1.3298
Epoch: 8/27... Step: 10770... Loss: 1.1952... Val Loss: 1.3275
Epoch: 8/27... Step: 10780... Loss: 1.1686... Val Loss: 1.3278
Epoch: 8/27... Step: 10790... Loss: 1.2057... Val Loss: 1.3257
Epoch: 8/27... Step: 10800... Loss: 1.2510... Val Loss:

Epoch: 9/27... Step: 11960... Loss: 1.1965... Val Loss: 1.3203
Epoch: 9/27... Step: 11970... Loss: 1.1917... Val Loss: 1.3185
Epoch: 9/27... Step: 11980... Loss: 1.2299... Val Loss: 1.3205
Epoch: 9/27... Step: 11990... Loss: 1.2070... Val Loss: 1.3280
Epoch: 9/27... Step: 12000... Loss: 1.1641... Val Loss: 1.3238
Epoch: 9/27... Step: 12010... Loss: 1.2023... Val Loss: 1.3154
Epoch: 9/27... Step: 12020... Loss: 1.1676... Val Loss: 1.3208
Epoch: 9/27... Step: 12030... Loss: 1.1681... Val Loss: 1.3241
Epoch: 9/27... Step: 12040... Loss: 1.2856... Val Loss: 1.3198
Epoch: 9/27... Step: 12050... Loss: 1.2456... Val Loss: 1.3197
Epoch: 9/27... Step: 12060... Loss: 1.2069... Val Loss: 1.3238
Epoch: 9/27... Step: 12070... Loss: 1.2224... Val Loss: 1.3232
Epoch: 9/27... Step: 12080... Loss: 1.2916... Val Loss: 1.3216
Epoch: 9/27... Step: 12090... Loss: 1.1665... Val Loss: 1.3228
Epoch: 9/27... Step: 12100... Loss: 1.1673... Val Loss: 1.3189
Epoch: 9/27... Step: 12110... Loss: 1.1921... Val Loss:

Epoch: 10/27... Step: 13250... Loss: 1.2035... Val Loss: 1.3194
Epoch: 10/27... Step: 13260... Loss: 1.1993... Val Loss: 1.3196
Epoch: 10/27... Step: 13270... Loss: 1.1849... Val Loss: 1.3184
Epoch: 10/27... Step: 13280... Loss: 1.1760... Val Loss: 1.3185
Epoch: 10/27... Step: 13290... Loss: 1.1578... Val Loss: 1.3206
Epoch: 10/27... Step: 13300... Loss: 1.2159... Val Loss: 1.3205
Epoch: 10/27... Step: 13310... Loss: 1.1435... Val Loss: 1.3189
Epoch: 10/27... Step: 13320... Loss: 1.1950... Val Loss: 1.3192
Epoch: 10/27... Step: 13330... Loss: 1.1687... Val Loss: 1.3235
Epoch: 10/27... Step: 13340... Loss: 1.2324... Val Loss: 1.3184
Epoch: 10/27... Step: 13350... Loss: 1.2056... Val Loss: 1.3162
Epoch: 10/27... Step: 13360... Loss: 1.1619... Val Loss: 1.3166
Epoch: 10/27... Step: 13370... Loss: 1.1783... Val Loss: 1.3134
Epoch: 10/27... Step: 13380... Loss: 1.1468... Val Loss: 1.3168
Epoch: 10/27... Step: 13390... Loss: 1.1472... Val Loss: 1.3188
Epoch: 10/27... Step: 13400... Loss: 1.2

Epoch: 11/27... Step: 14540... Loss: 1.1691... Val Loss: 1.3129
Epoch: 11/27... Step: 14550... Loss: 1.1615... Val Loss: 1.3183
Epoch: 11/27... Step: 14560... Loss: 1.1408... Val Loss: 1.3217
Epoch: 11/27... Step: 14570... Loss: 1.1867... Val Loss: 1.3202
Epoch: 11/27... Step: 14580... Loss: 1.2213... Val Loss: 1.3187
Epoch: 11/27... Step: 14590... Loss: 1.1504... Val Loss: 1.3176
Epoch: 11/27... Step: 14600... Loss: 1.1664... Val Loss: 1.3168
Epoch: 11/27... Step: 14610... Loss: 1.1795... Val Loss: 1.3180
Epoch: 11/27... Step: 14620... Loss: 1.1563... Val Loss: 1.3129
Epoch: 11/27... Step: 14630... Loss: 1.2488... Val Loss: 1.3136
Epoch: 11/27... Step: 14640... Loss: 1.2074... Val Loss: 1.3138
Epoch: 11/27... Step: 14650... Loss: 1.2544... Val Loss: 1.3145
Epoch: 11/27... Step: 14660... Loss: 1.1409... Val Loss: 1.3151
Epoch: 11/27... Step: 14670... Loss: 1.2102... Val Loss: 1.3163
Epoch: 11/27... Step: 14680... Loss: 1.1362... Val Loss: 1.3147
Epoch: 11/27... Step: 14690... Loss: 1.1

Epoch: 12/27... Step: 15830... Loss: 1.1450... Val Loss: 1.3075
Epoch: 12/27... Step: 15840... Loss: 1.2123... Val Loss: 1.3114
Epoch: 12/27... Step: 15850... Loss: 1.1273... Val Loss: 1.3099
Epoch: 12/27... Step: 15860... Loss: 1.1556... Val Loss: 1.3100
Epoch: 12/27... Step: 15870... Loss: 1.1718... Val Loss: 1.3078
Epoch: 12/27... Step: 15880... Loss: 1.1391... Val Loss: 1.3120
Epoch: 12/27... Step: 15890... Loss: 1.0849... Val Loss: 1.3172
Epoch: 12/27... Step: 15900... Loss: 1.1443... Val Loss: 1.3155
Epoch: 12/27... Step: 15910... Loss: 1.0690... Val Loss: 1.3156
Epoch: 12/27... Step: 15920... Loss: 1.1238... Val Loss: 1.3152
Epoch: 12/27... Step: 15930... Loss: 1.1499... Val Loss: 1.3133
Epoch: 12/27... Step: 15940... Loss: 1.1123... Val Loss: 1.3166
Epoch: 12/27... Step: 15950... Loss: 1.1675... Val Loss: 1.3190
Epoch: 12/27... Step: 15960... Loss: 1.1277... Val Loss: 1.3137
Epoch: 12/27... Step: 15970... Loss: 1.1826... Val Loss: 1.3139
Epoch: 12/27... Step: 15980... Loss: 1.1

Epoch: 13/27... Step: 17120... Loss: 1.2040... Val Loss: 1.3061
Epoch: 13/27... Step: 17130... Loss: 1.1483... Val Loss: 1.3127
Epoch: 13/27... Step: 17140... Loss: 1.1191... Val Loss: 1.3146
Epoch: 13/27... Step: 17150... Loss: 1.1539... Val Loss: 1.3117
Epoch: 13/27... Step: 17160... Loss: 1.1884... Val Loss: 1.3089
Epoch: 13/27... Step: 17170... Loss: 1.1619... Val Loss: 1.3106
Epoch: 13/27... Step: 17180... Loss: 1.2109... Val Loss: 1.3130
Epoch: 13/27... Step: 17190... Loss: 1.1496... Val Loss: 1.3083
Epoch: 13/27... Step: 17200... Loss: 1.2076... Val Loss: 1.3099
Epoch: 13/27... Step: 17210... Loss: 1.2189... Val Loss: 1.3121
Epoch: 13/27... Step: 17220... Loss: 1.1445... Val Loss: 1.3109
Epoch: 13/27... Step: 17230... Loss: 1.1144... Val Loss: 1.3124
Epoch: 13/27... Step: 17240... Loss: 1.1654... Val Loss: 1.3144
Epoch: 13/27... Step: 17250... Loss: 1.1526... Val Loss: 1.3076
Epoch: 13/27... Step: 17260... Loss: 1.2257... Val Loss: 1.3076
Epoch: 13/27... Step: 17270... Loss: 1.1

Epoch: 14/27... Step: 18410... Loss: 1.1567... Val Loss: 1.3100
Epoch: 14/27... Step: 18420... Loss: 1.1474... Val Loss: 1.3079
Epoch: 14/27... Step: 18430... Loss: 1.1977... Val Loss: 1.3094
Epoch: 14/27... Step: 18440... Loss: 1.1475... Val Loss: 1.3169
Epoch: 14/27... Step: 18450... Loss: 1.1499... Val Loss: 1.3158
Epoch: 14/27... Step: 18460... Loss: 1.1384... Val Loss: 1.3098
Epoch: 14/27... Step: 18470... Loss: 1.1422... Val Loss: 1.3094
Epoch: 14/27... Step: 18480... Loss: 1.1580... Val Loss: 1.3113
Epoch: 14/27... Step: 18490... Loss: 1.1798... Val Loss: 1.3113
Epoch: 14/27... Step: 18500... Loss: 1.1954... Val Loss: 1.3091
Epoch: 14/27... Step: 18510... Loss: 1.1993... Val Loss: 1.3084
Epoch: 14/27... Step: 18520... Loss: 1.1453... Val Loss: 1.3098
Epoch: 14/27... Step: 18530... Loss: 1.1406... Val Loss: 1.3146
Epoch: 14/27... Step: 18540... Loss: 1.1723... Val Loss: 1.3141
Epoch: 14/27... Step: 18550... Loss: 1.1435... Val Loss: 1.3126
Epoch: 14/27... Step: 18560... Loss: 1.0

Epoch: 15/27... Step: 19700... Loss: 1.1405... Val Loss: 1.3056
Epoch: 15/27... Step: 19710... Loss: 1.1748... Val Loss: 1.3077
Epoch: 15/27... Step: 19720... Loss: 1.1202... Val Loss: 1.3081
Epoch: 15/27... Step: 19730... Loss: 1.0991... Val Loss: 1.3099
Epoch: 15/27... Step: 19740... Loss: 1.1152... Val Loss: 1.3105
Epoch: 15/27... Step: 19750... Loss: 1.1923... Val Loss: 1.3112
Epoch: 15/27... Step: 19760... Loss: 1.1355... Val Loss: 1.3084
Epoch: 15/27... Step: 19770... Loss: 1.1489... Val Loss: 1.3080
Epoch: 15/27... Step: 19780... Loss: 1.0867... Val Loss: 1.3088
Epoch: 15/27... Step: 19790... Loss: 1.0887... Val Loss: 1.3069
Epoch: 15/27... Step: 19800... Loss: 0.9865... Val Loss: 1.3089
Epoch: 15/27... Step: 19810... Loss: 1.1466... Val Loss: 1.3097
Epoch: 15/27... Step: 19820... Loss: 1.1284... Val Loss: 1.3059
Epoch: 15/27... Step: 19830... Loss: 1.2037... Val Loss: 1.3088
Epoch: 15/27... Step: 19840... Loss: 1.1167... Val Loss: 1.3161
Epoch: 15/27... Step: 19850... Loss: 1.1

Epoch: 16/27... Step: 20990... Loss: 1.1393... Val Loss: 1.3067
Epoch: 16/27... Step: 21000... Loss: 1.1331... Val Loss: 1.3124
Epoch: 16/27... Step: 21010... Loss: 1.1155... Val Loss: 1.3180
Epoch: 16/27... Step: 21020... Loss: 1.1694... Val Loss: 1.3122
Epoch: 16/27... Step: 21030... Loss: 1.1076... Val Loss: 1.3108
Epoch: 16/27... Step: 21040... Loss: 1.1651... Val Loss: 1.3106
Epoch: 16/27... Step: 21050... Loss: 1.1283... Val Loss: 1.3061
Epoch: 16/27... Step: 21060... Loss: 1.1068... Val Loss: 1.3091
Epoch: 16/27... Step: 21070... Loss: 1.1492... Val Loss: 1.3139
Epoch: 16/27... Step: 21080... Loss: 1.1801... Val Loss: 1.3103
Epoch: 16/27... Step: 21090... Loss: 1.1276... Val Loss: 1.3081
Epoch: 16/27... Step: 21100... Loss: 1.1231... Val Loss: 1.3092
Epoch: 16/27... Step: 21110... Loss: 1.2160... Val Loss: 1.3114
Epoch: 16/27... Step: 21120... Loss: 1.1732... Val Loss: 1.3080
Epoch: 16/27... Step: 21130... Loss: 1.1211... Val Loss: 1.3077
Epoch: 16/27... Step: 21140... Loss: 1.1

Epoch: 16/27... Step: 22280... Loss: 1.0965... Val Loss: 1.3059
Epoch: 16/27... Step: 22290... Loss: 1.0800... Val Loss: 1.3069
Epoch: 16/27... Step: 22300... Loss: 1.0965... Val Loss: 1.3095
Epoch: 16/27... Step: 22310... Loss: 1.0959... Val Loss: 1.3104
Epoch: 16/27... Step: 22320... Loss: 1.7586... Val Loss: 1.3136
Epoch: 17/27... Step: 22330... Loss: 1.1378... Val Loss: 1.3127
Epoch: 17/27... Step: 22340... Loss: 1.1126... Val Loss: 1.3091
Epoch: 17/27... Step: 22350... Loss: 1.1520... Val Loss: 1.3079
Epoch: 17/27... Step: 22360... Loss: 1.1504... Val Loss: 1.3077
Epoch: 17/27... Step: 22370... Loss: 1.1404... Val Loss: 1.3114
Epoch: 17/27... Step: 22380... Loss: 1.1542... Val Loss: 1.3108
Epoch: 17/27... Step: 22390... Loss: 1.0952... Val Loss: 1.3098
Epoch: 17/27... Step: 22400... Loss: 1.0926... Val Loss: 1.3097
Epoch: 17/27... Step: 22410... Loss: 1.1158... Val Loss: 1.3149
Epoch: 17/27... Step: 22420... Loss: 1.1830... Val Loss: 1.3167
Epoch: 17/27... Step: 22430... Loss: 1.1

Epoch: 17/27... Step: 23570... Loss: 1.0972... Val Loss: 1.3118
Epoch: 17/27... Step: 23580... Loss: 1.1210... Val Loss: 1.3093
Epoch: 17/27... Step: 23590... Loss: 1.1405... Val Loss: 1.3083
Epoch: 17/27... Step: 23600... Loss: 1.1035... Val Loss: 1.3115
Epoch: 17/27... Step: 23610... Loss: 1.1370... Val Loss: 1.3131
Epoch: 17/27... Step: 23620... Loss: 1.1595... Val Loss: 1.3104
Epoch: 17/27... Step: 23630... Loss: 1.1802... Val Loss: 1.3102
Epoch: 17/27... Step: 23640... Loss: 1.1190... Val Loss: 1.3094
Epoch: 17/27... Step: 23650... Loss: 1.0811... Val Loss: 1.3153
Epoch: 17/27... Step: 23660... Loss: 1.1532... Val Loss: 1.3159
Epoch: 17/27... Step: 23670... Loss: 1.1647... Val Loss: 1.3093
Epoch: 17/27... Step: 23680... Loss: 1.0929... Val Loss: 1.3080
Epoch: 17/27... Step: 23690... Loss: 1.1575... Val Loss: 1.3106
Epoch: 17/27... Step: 23700... Loss: 1.1535... Val Loss: 1.3102
Epoch: 17/27... Step: 23710... Loss: 1.1559... Val Loss: 1.3091
Epoch: 18/27... Step: 23720... Loss: 1.1

Epoch: 18/27... Step: 24860... Loss: 1.1186... Val Loss: 1.3059
Epoch: 18/27... Step: 24870... Loss: 1.1053... Val Loss: 1.3086
Epoch: 18/27... Step: 24880... Loss: 1.1024... Val Loss: 1.3075
Epoch: 18/27... Step: 24890... Loss: 1.0984... Val Loss: 1.3060
Epoch: 18/27... Step: 24900... Loss: 1.1079... Val Loss: 1.3069
Epoch: 18/27... Step: 24910... Loss: 1.1206... Val Loss: 1.3108
Epoch: 18/27... Step: 24920... Loss: 1.0550... Val Loss: 1.3068
Epoch: 18/27... Step: 24930... Loss: 1.0365... Val Loss: 1.3066
Epoch: 18/27... Step: 24940... Loss: 1.1787... Val Loss: 1.3096
Epoch: 18/27... Step: 24950... Loss: 1.1481... Val Loss: 1.3111
Epoch: 18/27... Step: 24960... Loss: 1.1567... Val Loss: 1.3075
Epoch: 18/27... Step: 24970... Loss: 1.1660... Val Loss: 1.3069
Epoch: 18/27... Step: 24980... Loss: 1.1492... Val Loss: 1.3082
Epoch: 18/27... Step: 24990... Loss: 1.2004... Val Loss: 1.3063
Epoch: 18/27... Step: 25000... Loss: 1.1085... Val Loss: 1.3058
Epoch: 18/27... Step: 25010... Loss: 1.0

Epoch: 19/27... Step: 26150... Loss: 1.0737... Val Loss: 1.3063
Epoch: 19/27... Step: 26160... Loss: 1.0849... Val Loss: 1.3062
Epoch: 19/27... Step: 26170... Loss: 1.1042... Val Loss: 1.3082
Epoch: 19/27... Step: 26180... Loss: 1.1871... Val Loss: 1.3120
Epoch: 19/27... Step: 26190... Loss: 1.1279... Val Loss: 1.3105
Epoch: 19/27... Step: 26200... Loss: 1.0098... Val Loss: 1.3095
Epoch: 19/27... Step: 26210... Loss: 1.1401... Val Loss: 1.3078
Epoch: 19/27... Step: 26220... Loss: 1.1653... Val Loss: 1.3061
Epoch: 19/27... Step: 26230... Loss: 1.1255... Val Loss: 1.3052
Epoch: 19/27... Step: 26240... Loss: 1.0759... Val Loss: 1.3068
Epoch: 19/27... Step: 26250... Loss: 1.0728... Val Loss: 1.3077
Epoch: 19/27... Step: 26260... Loss: 1.0926... Val Loss: 1.3069
Epoch: 19/27... Step: 26270... Loss: 1.1407... Val Loss: 1.3083
Epoch: 19/27... Step: 26280... Loss: 1.1402... Val Loss: 1.3083
Epoch: 19/27... Step: 26290... Loss: 1.1414... Val Loss: 1.3082
Epoch: 19/27... Step: 26300... Loss: 1.1

Epoch: 20/27... Step: 27440... Loss: 1.1307... Val Loss: 1.3119
Epoch: 20/27... Step: 27450... Loss: 1.1770... Val Loss: 1.3071
Epoch: 20/27... Step: 27460... Loss: 1.1123... Val Loss: 1.3042
Epoch: 20/27... Step: 27470... Loss: 1.1272... Val Loss: 1.3014
Epoch: 20/27... Step: 27480... Loss: 1.1234... Val Loss: 1.3083
Epoch: 20/27... Step: 27490... Loss: 1.1761... Val Loss: 1.3119
Epoch: 20/27... Step: 27500... Loss: 1.1290... Val Loss: 1.3096
Epoch: 20/27... Step: 27510... Loss: 1.0999... Val Loss: 1.3078
Epoch: 20/27... Step: 27520... Loss: 1.0924... Val Loss: 1.3079
Epoch: 20/27... Step: 27530... Loss: 1.1253... Val Loss: 1.3079
Epoch: 20/27... Step: 27540... Loss: 1.1622... Val Loss: 1.3093
Epoch: 20/27... Step: 27550... Loss: 1.1396... Val Loss: 1.3061
Epoch: 20/27... Step: 27560... Loss: 1.1230... Val Loss: 1.3064
Epoch: 20/27... Step: 27570... Loss: 1.1401... Val Loss: 1.3116
Epoch: 20/27... Step: 27580... Loss: 1.1005... Val Loss: 1.3135
Epoch: 20/27... Step: 27590... Loss: 1.1

Epoch: 21/27... Step: 28730... Loss: 1.1207... Val Loss: 1.3082
Epoch: 21/27... Step: 28740... Loss: 1.0590... Val Loss: 1.3126
Epoch: 21/27... Step: 28750... Loss: 1.1096... Val Loss: 1.3065
Epoch: 21/27... Step: 28760... Loss: 1.0914... Val Loss: 1.3039
Epoch: 21/27... Step: 28770... Loss: 1.1042... Val Loss: 1.3088
Epoch: 21/27... Step: 28780... Loss: 1.1665... Val Loss: 1.3107
Epoch: 21/27... Step: 28790... Loss: 1.1582... Val Loss: 1.3133
Epoch: 21/27... Step: 28800... Loss: 1.1356... Val Loss: 1.3125
Epoch: 21/27... Step: 28810... Loss: 1.1285... Val Loss: 1.3094
Epoch: 21/27... Step: 28820... Loss: 1.1926... Val Loss: 1.3076
Epoch: 21/27... Step: 28830... Loss: 1.1204... Val Loss: 1.3080
Epoch: 21/27... Step: 28840... Loss: 1.0845... Val Loss: 1.3071
Epoch: 21/27... Step: 28850... Loss: 1.1047... Val Loss: 1.3058
Epoch: 21/27... Step: 28860... Loss: 1.2018... Val Loss: 1.3067
Epoch: 21/27... Step: 28870... Loss: 1.0657... Val Loss: 1.3049
Epoch: 21/27... Step: 28880... Loss: 1.1

Epoch: 22/27... Step: 30020... Loss: 1.1112... Val Loss: 1.3103
Epoch: 22/27... Step: 30030... Loss: 1.0967... Val Loss: 1.3114
Epoch: 22/27... Step: 30040... Loss: 1.1353... Val Loss: 1.3120
Epoch: 22/27... Step: 30050... Loss: 1.0664... Val Loss: 1.3107
Epoch: 22/27... Step: 30060... Loss: 1.1092... Val Loss: 1.3063
Epoch: 22/27... Step: 30070... Loss: 1.0836... Val Loss: 1.3098
Epoch: 22/27... Step: 30080... Loss: 1.1462... Val Loss: 1.3096
Epoch: 22/27... Step: 30090... Loss: 1.0826... Val Loss: 1.3081
Epoch: 22/27... Step: 30100... Loss: 1.1140... Val Loss: 1.3076
Epoch: 22/27... Step: 30110... Loss: 1.1163... Val Loss: 1.3043
Epoch: 22/27... Step: 30120... Loss: 1.1056... Val Loss: 1.3045
Epoch: 22/27... Step: 30130... Loss: 1.0911... Val Loss: 1.3059
Epoch: 22/27... Step: 30140... Loss: 1.1514... Val Loss: 1.3082
Epoch: 22/27... Step: 30150... Loss: 1.0817... Val Loss: 1.3042
Epoch: 22/27... Step: 30160... Loss: 1.1246... Val Loss: 1.3044
Epoch: 22/27... Step: 30170... Loss: 1.1

Epoch: 23/27... Step: 31310... Loss: 1.1460... Val Loss: 1.3114
Epoch: 23/27... Step: 31320... Loss: 1.1697... Val Loss: 1.3109
Epoch: 23/27... Step: 31330... Loss: 1.1110... Val Loss: 1.3139
Epoch: 23/27... Step: 31340... Loss: 1.0831... Val Loss: 1.3195
Epoch: 23/27... Step: 31350... Loss: 1.1128... Val Loss: 1.3145
Epoch: 23/27... Step: 31360... Loss: 1.0904... Val Loss: 1.3081
Epoch: 23/27... Step: 31370... Loss: 1.1516... Val Loss: 1.3077
Epoch: 23/27... Step: 31380... Loss: 1.1465... Val Loss: 1.3142
Epoch: 23/27... Step: 31390... Loss: 1.1674... Val Loss: 1.3142
Epoch: 23/27... Step: 31400... Loss: 1.0891... Val Loss: 1.3106
Epoch: 23/27... Step: 31410... Loss: 1.1201... Val Loss: 1.3098
Epoch: 23/27... Step: 31420... Loss: 1.0522... Val Loss: 1.3097
Epoch: 23/27... Step: 31430... Loss: 1.0803... Val Loss: 1.3130
Epoch: 23/27... Step: 31440... Loss: 1.1343... Val Loss: 1.3134
Epoch: 23/27... Step: 31450... Loss: 1.1058... Val Loss: 1.3107
Epoch: 23/27... Step: 31460... Loss: 1.0

Epoch: 24/27... Step: 32600... Loss: 1.0990... Val Loss: 1.3043
Epoch: 24/27... Step: 32610... Loss: 1.0996... Val Loss: 1.3036
Epoch: 24/27... Step: 32620... Loss: 1.0646... Val Loss: 1.3052
Epoch: 24/27... Step: 32630... Loss: 1.0499... Val Loss: 1.3120
Epoch: 24/27... Step: 32640... Loss: 1.0414... Val Loss: 1.3161
Epoch: 24/27... Step: 32650... Loss: 1.0384... Val Loss: 1.3127
Epoch: 24/27... Step: 32660... Loss: 1.0393... Val Loss: 1.3085
Epoch: 24/27... Step: 32670... Loss: 1.0911... Val Loss: 1.3095
Epoch: 24/27... Step: 32680... Loss: 1.0532... Val Loss: 1.3143
Epoch: 24/27... Step: 32690... Loss: 1.1075... Val Loss: 1.3140
Epoch: 24/27... Step: 32700... Loss: 1.0686... Val Loss: 1.3108
Epoch: 24/27... Step: 32710... Loss: 1.1164... Val Loss: 1.3104
Epoch: 24/27... Step: 32720... Loss: 1.0599... Val Loss: 1.3102
Epoch: 24/27... Step: 32730... Loss: 1.1664... Val Loss: 1.3126
Epoch: 24/27... Step: 32740... Loss: 1.1175... Val Loss: 1.3177
Epoch: 24/27... Step: 32750... Loss: 1.1

Epoch: 25/27... Step: 33890... Loss: 1.1154... Val Loss: 1.3116
Epoch: 25/27... Step: 33900... Loss: 1.1135... Val Loss: 1.3085
Epoch: 25/27... Step: 33910... Loss: 1.1174... Val Loss: 1.3077
Epoch: 25/27... Step: 33920... Loss: 1.1591... Val Loss: 1.3095
Epoch: 25/27... Step: 33930... Loss: 1.1332... Val Loss: 1.3058
Epoch: 25/27... Step: 33940... Loss: 1.1494... Val Loss: 1.3039
Epoch: 25/27... Step: 33950... Loss: 1.1757... Val Loss: 1.3042
Epoch: 25/27... Step: 33960... Loss: 1.0713... Val Loss: 1.3087
Epoch: 25/27... Step: 33970... Loss: 1.0347... Val Loss: 1.3108
Epoch: 25/27... Step: 33980... Loss: 1.1171... Val Loss: 1.3106
Epoch: 25/27... Step: 33990... Loss: 1.0919... Val Loss: 1.3057
Epoch: 25/27... Step: 34000... Loss: 1.1430... Val Loss: 1.3065
Epoch: 25/27... Step: 34010... Loss: 1.0496... Val Loss: 1.3061
Epoch: 25/27... Step: 34020... Loss: 1.0558... Val Loss: 1.3101
Epoch: 25/27... Step: 34030... Loss: 1.1164... Val Loss: 1.3150
Epoch: 25/27... Step: 34040... Loss: 1.0

Epoch: 26/27... Step: 35180... Loss: 1.0655... Val Loss: 1.3120
Epoch: 26/27... Step: 35190... Loss: 1.0927... Val Loss: 1.3155
Epoch: 26/27... Step: 35200... Loss: 1.0587... Val Loss: 1.3149
Epoch: 26/27... Step: 35210... Loss: 1.0707... Val Loss: 1.3097
Epoch: 26/27... Step: 35220... Loss: 1.0836... Val Loss: 1.3070
Epoch: 26/27... Step: 35230... Loss: 1.0734... Val Loss: 1.3053
Epoch: 26/27... Step: 35240... Loss: 1.1127... Val Loss: 1.3049
Epoch: 26/27... Step: 35250... Loss: 1.1390... Val Loss: 1.3053
Epoch: 26/27... Step: 35260... Loss: 1.0695... Val Loss: 1.3062
Epoch: 26/27... Step: 35270... Loss: 1.0887... Val Loss: 1.3124
Epoch: 26/27... Step: 35280... Loss: 1.1316... Val Loss: 1.3145
Epoch: 26/27... Step: 35290... Loss: 1.0941... Val Loss: 1.3116
Epoch: 26/27... Step: 35300... Loss: 1.0382... Val Loss: 1.3060
Epoch: 26/27... Step: 35310... Loss: 1.1510... Val Loss: 1.3059
Epoch: 26/27... Step: 35320... Loss: 1.0717... Val Loss: 1.3089
Epoch: 26/27... Step: 35330... Loss: 1.0

Epoch: 27/27... Step: 36470... Loss: 1.0573... Val Loss: 1.3056
Epoch: 27/27... Step: 36480... Loss: 1.0441... Val Loss: 1.3064
Epoch: 27/27... Step: 36490... Loss: 1.0905... Val Loss: 1.3103
Epoch: 27/27... Step: 36500... Loss: 1.0850... Val Loss: 1.3074
Epoch: 27/27... Step: 36510... Loss: 1.1027... Val Loss: 1.3064
Epoch: 27/27... Step: 36520... Loss: 1.0297... Val Loss: 1.3045
Epoch: 27/27... Step: 36530... Loss: 1.0164... Val Loss: 1.3061
Epoch: 27/27... Step: 36540... Loss: 0.9933... Val Loss: 1.3077
Epoch: 27/27... Step: 36550... Loss: 1.1102... Val Loss: 1.3088
Epoch: 27/27... Step: 36560... Loss: 1.0813... Val Loss: 1.3079
Epoch: 27/27... Step: 36570... Loss: 1.1390... Val Loss: 1.3091
Epoch: 27/27... Step: 36580... Loss: 1.0921... Val Loss: 1.3146
Epoch: 27/27... Step: 36590... Loss: 1.0571... Val Loss: 1.3164
Epoch: 27/27... Step: 36600... Loss: 1.0983... Val Loss: 1.3113
Epoch: 27/27... Step: 36610... Loss: 1.1031... Val Loss: 1.3076
Epoch: 27/27... Step: 36620... Loss: 1.1

## Checkpoint

Saving model

In [16]:
# change the name, for saving multiple files
model_name = 'rnn.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

---
## Making Predictions

In [17]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

### Priming and generating text 

In [18]:
def sample(net, size, prime='The', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [23]:
print(sample(net, 1000, prime='train', top_k=5))

train they can study in the world was
the first time had before a look with the child, so that those thought to be a crop when
she was asleep
he had not answered what he was seeing him to anyone that
he was ashamed, the footman
and
this party had time to see him that she was
so satisfied, were in a solemal and the feeling of carriage and the compenit entering a sting, who had still
more, and the sick man had. That would have spent the music and drawing her all these weight, and he did
not see what to do all, his wife had been
carrying at the same time, and he had seen them. He did not say that he diversed the portfolio, and had thruwted her he was not to speak of all that he had arrived, though their
family
she was seriously that he had seen his study, and serious and a merchant's secret clack of his strange thing absorbed him any one of the count, who had
answered shrills on the pitiful position, and he
had been a sense of tone, the future still had so the point of clever her husband 

## Loading a checkpoint

In [20]:
# Here we have loaded in a model
with open('rnn.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

In [21]:
# Sample using a loaded model
print(sample(loaded, 2000, top_k=5, prime="And Levin said"))

And Levin said, and the carriage he had an understand himself, as he went off to the little conception.

"Oh, yes, this woman is so a langer he doesn't say something," he said, sitting down by
her.

"Yes, that's nothing?" she asked herself.
"I was not so left alone, but I'm such a little, and though I can did not think of you."

"Oh, yes, that you
more about it. And what,
if I do not advise you to do, I'm going to
the memaronity and thoughts of it....
I'd better be the second and telling you to
them to blame, and so introduces itself. It's not this, if I would be in subjects of
my life, but when she came to tell her anything
without the steps to her again, and he had
to be dull for the same position; but and he was stupid
indeed and that there was not telling the stream of any opportonity of the same
past of the strange few
masters. He felt that he had
talked
without stayed on at the sick man, he had better never accessing him.

"I'm not given in that woman. What's true to that, but yo